{
 "title": "Elasticsearch ambassador Logs",
 "description": "Browse, analyze logs in Elasticsearchstatus_codes, pie-chart, top 10 clientip, line-chart,word-map and etc...",
 "tags": [
  "nginx",
  "es",
  "logstash",
  "log"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "域名",
    "query": "{\"find\":\"terms\",\"field\":\"domain.keyword\"}"
   },
   {
    "name": "status",
    "label": "状态码",
    "query": "{\"find\":\"terms\",\"field\":\"response_code.keyword\"}"
   },
   { "name": "responsetime", "label": "请求时间", "query": "1,2,3,4,5,10" },
   {
    "name": "inter",
    "label": "周期",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "汇总", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "全站请求总数",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain:*",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "请求总数",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "IP访问数",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "client_ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain HTTP 状态码",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "response_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain IP TOP 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "client_ip.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain 访问前十的城市",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "city.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain 访问前十的省份",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "region_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain 国家/地区访问占比",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain 请求方法占比",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "method.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain Word Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain request top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "request 404  top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND response_code: 404",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "request 503  top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND response_code: 503",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain referer top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "referer.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain user_agent top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "user-agent.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  { "title": "历史趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "$domain 请求数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain HTTP 状态码",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "none", "label": "状态码数量" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "response_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain 慢响应 时间>$responsetime s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND responsetime:[$responsetime TO 100000]",
     "timeField": "log_time"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "$domain status:$status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "domain:$domain and status:$status",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "$domain 所有接口平均响应时间",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 132 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "duration.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "domain:$domain",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "log_time"
    }
   ]
  }
 ]
}